// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxpynibolvilwdbnajqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cHluaWJvbHZpbHdkYm5hanF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MTc2MDEsImV4cCI6MjA2MTk5MzYwMX0.0koVh5YwMCYMPfdoOuxtCDp1UPLM_ELnVTTVGLWOcPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);